fix: exception occurred deleting files
Azure-Samples/chat-with-your-data-solution-accelerator pull request #1110
Opened 2024-07-04 07:41 UTC by Prashant-Microsoft

## Purpose
Exception occurred deleting files
* ...

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## How to Test
*  In the admin site if you go to delete data section, then you will get the exception

```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
npm install
```

* Test the code

```
```

## What to Check
Verify that the following are valid

- Launch the admin site and navigate to delete data section

2024-07-04 08:09 UTC, adamdougal requested changes
Do we know under what circumstances this can happen? Do you have a copy or a screenshot of the error? Thanks

2024-07-04 08:09 UTC, adamdougal commented on code/backend/batch/utilities/search/integrated_vectorization_search_handler.py
> +            if result["chunk_id"] is not None and result["title"] is not None:
Can we add a unit test for this case?

2024-07-05 03:12 UTC, Prashant-Microsoft commented
> Do we know under what circumstances this can happen? Do you have a copy or a screenshot of the error? Thanks

In some of the documents we are getting title field as null, that case it will give us error
<img width="629" alt="image" src="https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/assets/169637670/c152deb4-6991-416a-984c-d28313fecf5b">

2024-07-05 08:15 UTC, adamdougal commented
Gotcha! My concern with this fix is that, yes it stops the exception, but it also stops the file being outputted, which means it cannot be deleted.

Could we address the issue of the title not being there instead?

2024-07-05 09:13 UTC, Roopan-Microsoft commented
> Gotcha! My concern with this fix is that, yes it stops the exception, but it also stops the file being outputted, which means it cannot be deleted.
> 
> Could we address the issue of the title not being there instead?

Yes @adamdougal - We are also trying the same scenario to repro that issue. Will figure it out

2024-07-05 13:48 UTC, Prashant-Microsoft commented
> Gotcha! My concern with this fix is that, yes it stops the exception, but it also stops the file being outputted, which means it cannot be deleted.
> 
> Could we address the issue of the title not being there instead?

@adamdougal Seems like this issue is intermittent, now we are not able to get the title field as null, everything working properly but still, we are working on it to repro the issue

2024-07-05 13:49 UTC, Prashant-Microsoft commented
> Gotcha! My concern with this fix is that, yes it stops the exception, but it also stops the file being outputted, which means it cannot be deleted.
> 
> Could we address the issue of the title not being there instead?

@adamdougal Seems like this issue is intermittent, now we are not able to get the title field as null, everything working properly but still, we are working on it to repro the issue

2024-07-10 13:16 UTC, adamdougal commented
Closing as we can't reproduce the error.

2024-07-10 13:16 UTC, closed without merging