Draft Chat History
Azure-Samples/chat-with-your-data-solution-accelerator pull request #1288
Opened 2024-09-04 15:17 UTC by Fr4nc3

## Purpose

* ...

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## How to Test
*  Get the code

```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
npm install
```

* Test the code

```
```

## What to Check
Verify that the following are valid
* ...

## Other Information

2024-09-04 22:13 UTC, Fr4nc3 commented on .vscode/launch.json
this need to be rollback before final PR

2024-09-04 22:13 UTC, Fr4nc3 commented on Pipfile
This need to be git ignored before final PR

2024-09-04 22:14 UTC, Fr4nc3 commented on Pipfile.lock
This need to be gitignore before the final PR

2024-09-04 22:14 UTC, Fr4nc3 commented on code/backend/batch/function_app.py
> +    http_auth_level=func.AuthLevel.ANONYMOUS,
this need to be rolled back before final PR

2024-09-04 22:14 UTC, Fr4nc3 commented on code/backend/batch/utilities/helpers/config/config_helper.py
> -        env_helper = EnvHelper()
this needs to be rolled back before final PR

2024-09-04 22:15 UTC, Fr4nc3 commented on code/backend/batch/utilities/helpers/env_helper.py
> +        print(os.environ)
this needs to be rolled back before final PR

2024-09-04 22:15 UTC, Fr4nc3 commented on code/frontend/vite.config.ts
> -                target: "http://127.0.0.1:5050",
this need to be rolled back before final PR

2024-09-27 21:02 UTC, marktayl1 reviewed
Just found the pip file thing.

2024-09-27 21:19 UTC, marktayl1 approved these changes
Test approval per Francia's request.  Do not merge.

2024-09-27 21:23 UTC, marktayl1 requested changes
test

2024-09-30 19:59 UTC, marktayl1 approved these changes

2024-09-30 20:25 UTC, Vinay-Microsoft approved these changes

2024-09-30 20:38 UTC, Vinay-Microsoft approved these changes

2024-09-30 20:41 UTC, merged

2024-10-10 00:09 UTC, ross-p-smith commented
@Fr4nc3, @Vinay-Microsoft - this PR seems like it has commented out tests and linting - do you have a plan to put these back?

2024-11-05 20:02 UTC, ross-p-smith commented
Closes #85