Update placeholder value for function URL
Azure-Samples/chat-with-your-data-solution-accelerator pull request #806
Opened 2024-05-03 13:25 UTC by frtibble

## Purpose
As described in #561, the placeholder values used in `AZURE_FUNCTION_URL` need updating. The current URL value uses `<DEPLOYMENT_PREFIX>-backend`.

However, our function name now uses the formatting: https://github.com/Azure-Samples/chat-with-your-data-solution-accelerator/blob/3705186528decdbcfc711f0e0ca3d4206d50f272/infra/main.bicep#L214

This PR updates the documentation and `.env` files to reflect this.

Fixes #561 

## Does this introduce a breaking change?
- [ ] Yes
- [x] No

## Pull Request Type
What kind of change does this Pull Request introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [X] Documentation content changes
- [ ] Other... Please describe:

## How to Test
n/a

2024-05-03 13:48 UTC, ross-p-smith commented on docs/TEAMS_EXTENSION.md
>      AZURE_FUNCTION_URL=https://<DEPLOYMENT_PREFIX>-backend.azurewebsites.net/api/GetConversationResponse?code=<FUNCTION_APP_CLIENT_KEY>&clientId=clientKey
```suggestion
    AZURE_FUNCTION_URL=https://<RESOURCE_TOKEN>-backend.azurewebsites.net/api/GetConversationResponse?code=<FUNCTION_APP_CLIENT_KEY>&clientId=clientKey
```

2024-05-03 13:52 UTC, ross-p-smith requested changes
Thanks Francis (Small addition required). Also if you amend the main comment of your PR to be "Fixes #561" then it will automatically link the issue/pr for you

2024-05-05 10:56 UTC, superhindupur approved these changes

2024-05-07 06:15 UTC, ross-p-smith approved these changes

2024-05-07 08:11 UTC, merged