Add documentation for integrated vectorization.
Azure-Samples/chat-with-your-data-solution-accelerator pull request #834
Opened 2024-05-08 07:45 UTC by superhindupur

## Purpose
This PR adds a section to the README on Integrated Vectorization that links to a page that describes how to deploy it. 
Required by #761.

## Does this introduce a breaking change?

```
[ ] Yes
[x] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[x] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
n/a

2024-05-08 07:57 UTC, adamdougal approved these changes
![lgtm](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExb21sNjN5cHd0MjlmdHRzZGppOWtsYmZ3eXdsbmxobzR4dWpkb2sxNCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/3o7aDa022Z5JIgsKkg/giphy.gif)

2024-05-08 07:59 UTC, ross-p-smith submitted a review, later dismissed

2024-05-08 08:49 UTC, adamdougal requested changes
As discussed can we add a section about the inability to switch between push and pull.

2024-05-08 09:08 UTC, komalg1 commented
This is great. Just a couple of things we can add
- we should tell users that they can select IV as true when they first deploy (Deploy to Azure button)
- Also IV can be selected on a fresh deployment (when the index has not yet been created)
- In case anyone wants to migrate they can delete the index in case of push & in case of pull delete index, indexer, datasource, skillset

Also, shall we hold on this merge till the time all IV changes are pushed in?

2024-05-08 12:54 UTC, frtibble commented
Looks great! Once the IV changes are in, I'd be happy to go through the docs/steps to test it out as a user fresh to it.

2024-05-08 13:16 UTC, gaurarpit submitted a review, later dismissed
LGTM

```
           (`-,-,
           ('(_,( )
            _   `_'
         __|_|__|_|_
       _|___________|__
      |o o o o o o o o/   
     ~'`~'`~'`~'`~'`~'`~
```

2024-05-08 19:04 UTC, ross-p-smith commented on docs/INTEGRATED_VECTORIZATION.md
> +This feature allows chunking and vectorization of data during ingestion into Azure AI Search through built-in pull-indexers. It supports automatic processing of data directly from storage - meaning t
Can we add a link to https://learn.microsoft.com/en-us/azure/search/vector-search-integrated-vectorization

2024-05-10 13:03 UTC, adamdougal approved these changes
![lgtm](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExNzI4ZGl6cHUyeGkxb2FieW16OTZubXo3cmFmdHFhNTUyYXJvc3ZwYyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/l3mZfxgPWhmuXa8Cc/giphy.gif)

2024-05-10 14:54 UTC, merged